/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.support.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Test service. Represents a row in the &quot;hd_Test&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.support.model.impl.TestModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.support.model.impl.TestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Test
 * @see com.liferay.support.model.impl.TestImpl
 * @see com.liferay.support.model.impl.TestModelImpl
 * @generated
 */
public interface TestModel extends BaseModel<Test> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a test model instance should use the {@link Test} interface instead.
	 */

	/**
	 * Returns the primary key of this test.
	 *
	 * @return the primary key of this test
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this test.
	 *
	 * @param primaryKey the primary key of this test
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the test ID of this test.
	 *
	 * @return the test ID of this test
	 */
	public long getTestId();

	/**
	 * Sets the test ID of this test.
	 *
	 * @param testId the test ID of this test
	 */
	public void setTestId(long testId);

	/**
	 * Returns the company ID of this test.
	 *
	 * @return the company ID of this test
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this test.
	 *
	 * @param companyId the company ID of this test
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this test.
	 *
	 * @return the user ID of this test
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this test.
	 *
	 * @param userId the user ID of this test
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this test.
	 *
	 * @return the user uuid of this test
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this test.
	 *
	 * @param userUuid the user uuid of this test
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the test of this test.
	 *
	 * @return the test of this test
	 */
	@AutoEscape
	public String getTest();

	/**
	 * Sets the test of this test.
	 *
	 * @param test the test of this test
	 */
	public void setTest(String test);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Test test);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Test> toCacheModel();

	@Override
	public Test toEscapedModel();

	@Override
	public Test toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}